---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: "./src/xml"
  label: XML
  create: documents
  match: "*.xml"
  new_doc_ext: xml
- type: document
  path: "./src/posts"
  label: Page
upload_dir: "./src/posts/image"
public_path: "./image"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: deno run -A https://deno.land/x/lume/install.js
  preview_docker_image: https://hub.docker.com/r/denoland/deno
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: lume --serve
