---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: src/posts
  label: Pages
  create: documents
  match: "*.md"
  exclude: _data.yml
  new_doc_ext: md
- type: directory
  path: src/midi
  label: MIDI
  create: none
  match: "*.mid"
- type: document
  path: src/about.md
  label: About
- type: directory
  path: src/musicxml
  label: MusicXML
  create: none
  match: "*.xml *.musicxml *.mxl"
  new_doc_ext: xml
- type: document
  path: src/_data/site.yml
  label: Settings
upload_dir: ''
public_path: https://res.cloudinary.com/neroblackstone/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: deno --version
  preview_docker_image: denoland/deno:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: deno run -A https://deno.land/x/lume/ci.js --serve
