---
title: Welcome to my blog !
description: "(其实这只是个笔记本啦~~)"
author:
  url: https://neroblackstone-blog.pages.dev/
  name: Nero Blackstone
  bio: Another scum
  photoPath: https://res.cloudinary.com/neroblackstone/image/upload/v1624180735/zeke_ao5xno.webp
  twitter: https://twitter.com/Fl0ydCampbell
  youtube: https://odysee.com/@NeroBlackstone:b
  github: https://github.com/NeroBlackstone
  email: gf7600gs@gmail.com
footer: 
friends:
- name: SgDylan
  photoPath: https://res.cloudinary.com/neroblackstone/image/upload/v1624180746/SgDylan_qmbdo3.webp
  bio: 是喵喵喵!
  link: https://blog.sgdylan.com/
- name: Oscar Otero
  photoPath: https://res.cloudinary.com/neroblackstone/image/upload/v1624180746/Oscar_cakgrj.webp
  bio: Web designer and developer, maintainer of lume
  link: https://oscarotero.com/
postsPerPage: "5"
indexPostNum: "5"
autoDarkMode: false
darkMode: true
disqus:
  enable: true
  shortname: neroblackstones-blog
cloudflareWebAnalytics:
  enable: true
  token: 5419c068361b4a1abf6d673ce3a1a7fe
version:
  lume: 0.25.0
  bulma: 0.9.3
